### PR TITLE
Cleanup icepack_shortwave_data

### PR DESCRIPTION
**Pull request by apcraig**
- Rename variables to gaer/kaer/waer/bcenh for 3 and 5 band
- Add 3 band gaer/kaer/waer/bcenh data
- Eliminate ability to pass SSP SNICAR data in thru icepack_parameters
- Remove nmodal1, nmodal2, max_aero redundant definitions, use values in icepack_tracers
- Change module hierarchy, icepack_parameters now "under" icepack_shortwave_data
- Rename nmbrad in icepack_shortwave_data to nmbrad_snw

### CODE REVIEW

**Comment by apcraig** [comment]
This is the next step, cleaning up the icepack_shortwave_data module and ramifications of that.  There is still some 3 band data missing.  Also, it looks like the gaer/kaer/waer/bcenh is not being using at the moment, even with snicar on, not sure why.  Those fields from the data tables was never set in icepack_shortwave.  We may need to briefly discuss that before next steps.

I'm running tests now to make sure baseline (non-snicar) results are bit-for-bit.

**Review by eclare108213 — APPROVED** [review]
This makes a lot more sense to me.  Are you ready for it to be merged?

**Comment by apcraig** [comment]
Let me just verify that it's bit-for-bit in the testing, should take an hour or so, I'll let you know here, then lets merge.  If you want to chat briefly about the gaer/kaer/waer/bcenh fields in icepack_shortwave, that would be helpful too, if you have a chance.  Thanks.

**Comment by eclare108213** [comment]
Aerosols probably have to be turned on in order to exercise gaer etc.  
Github actions failed...

**Comment by apcraig** [comment]
I'm working on the github actions now.  OK, if aerosols need to be on, that's good to know.  thanks.

**Comment by apcraig** [comment]
I think all is good now.  Github actions passes as do the bit-for-bit testing I did on cheyenne.  This can be merged.

**Pull request merged**
