### PR TITLE
Update ssp output

### PR DESCRIPTION
**Pull request by apcraig**
This updates the SSP output for testing and validation.

### CODE REVIEW

**Comment by apcraig** [comment]
This output clearly shows a problems with the input data.  The SSP data read in from the file is ordered differently than the data in the 5x5 test table.  My guess is that the 5x5 test table is wrong as that would mean the snicar_5bnd_snow_short.text file is correct as defined.  I'll need to reorder the data statement to match up with the order the arrays are defined in the code.

**Comment by apcraig** [comment]
I updated the SNICAR SSP data statement and the data order now seems consistent with the bigger table that is read in by the icepack driver.  I am fairly confident that both are now correct.  Some sample output is written to the log file and could be checked with the experts, that looks like

```
 # Big table in file
 (icepack_init_radiation) nmbrad_snicar =     1471
 (icepack_init_radiation) nspint =        5
 (icepack_init_radiation) ssp_snwextdr(    1,    1) =   55.65840
 (icepack_init_radiation) ssp_snwextdr(    5,    1) =   57.30311
 (icepack_init_radiation) ssp_snwextdr(    1, 1471) =   1.092800
 (icepack_init_radiation) ssp_snwextdr(    5, 1471) =   1.095214

 # Test data 5x5
 (icepack_init_radiation) nmbrad_snicar =        5
 (icepack_init_radiation) nspint =        5
 (icepack_init_radiation) ssp_snwextdr(    1,    1) =   46.27375
 (icepack_init_radiation) ssp_snwextdr(    5,    1) =   47.48598
 (icepack_init_radiation) ssp_snwextdr(    1,    5) =   1.196168
 (icepack_init_radiation) ssp_snwextdr(    5,    5) =   1.198974
```

**Comment by apcraig** [comment]
I have run some tests, the dEdd_snicar option still fails at run time.  But I think this should be merged.

**Comment by eclare108213** [comment]
I haven't connected the proper forcing data for the dEdd_snicar option yet, so it isn't expected to run.  This PR will definitely help with that task.  Thank you!

**Pull request merged**
