### PR TITLE
snicar branch rebase to E3SM Icepack #4ff4328 Aug 17, 2022

### PR DESCRIPTION
**Pull request by apcraig**
snicar branch rebase to E3SM Icepack cice-consortium/E3SM-icepack-initial-integration #4ff4328 Aug 17, 2022

### CODE REVIEW

**Comment by apcraig** [comment]
I believe this rebases the snicar branch to the current E3SM-Project Icepack cice-consortium/E3SM-icepack-initial-integration branch and re-cleans up the extra spaces/tabs.

If this is merged, it's just like you checked out the E3SM-Project branch and then made changes on it.   I think that would be useful if you want to continue to work on the snicar branch moving forward.  If you prefer to create a new branch or do something different, that's fine too.  In that case, feel free to close this PR.

Once this PR is merged, I will check history and diff the code vs other branches to make sure it's nice and clean.

**Comment by apcraig** [comment]
By the way, I haven't done any testing with this yet.  I will try to build and run an Icepack case.  You might want to do the same just to make sure nothing is broken.

**Comment by apcraig** [comment]
This is interesting, clean up of trailing blanks leads to conflicts.  Err!!!  Will close and try some other stuff.

**Comment by eclare108213** [comment]
Yes, that's why I ended up just replacing the entire icepack_shortwave.F90 module in my original snicar branch.

**Pull request closed without merging**
